Write a Numpy program to get the Numpy version.

In [1]:
# Importing the NumPy library with an alias 'np'
import numpy as np

# Printing the version of NumPy installed
print(np.__version__)

# Printing the configuration details of NumPy
print(np.show_config())

1.25.2
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS

Write a NumPy program to test whether none of the
elements of a given array are zero.

In [3]:
import numpy as np
x = np.array([1, 2, 3, 4])
print("Original array:")
print(x)
print("Test if none of the elements of the said array is zero:")
print(np.all(x))

Original array:
[1 2 3 4]
Test if none of the elements of the said array is zero:
True


In [5]:
import numpy as np
x = np.array([0,1,2,3])
print("original array:")
print(x)
print("Test if none oof the element of the said array is zero:")
print(np,all(x))

original array:
[0 1 2 3]
Test if none oof the element of the said array is zero:
<module 'numpy' from '/usr/local/lib/python3.10/dist-packages/numpy/__init__.py'> False


Write a NumPy program to create an element-wise
comparison (greater, greater_equal, less and less_equal) of
two given arrays.


In [6]:
import numpy as np

x = np.array([4, 5])
y = np.array([5, 5])

print("Original numbers:")
print(x)
print(y)

print("Comparison - greater")
print(np.greater(x, y))

print("Comparison - greater_equal")
print(np.greater_equal(x, y))

print("Comparison - less")
print(np.less(x, y))

print("Comparison - less_equal")
print(np.less_equal(x, y))

Original numbers:
[4 5]
[5 5]
Comparison - greater
[False False]
Comparison - greater_equal
[False  True]
Comparison - less
[ True False]
Comparison - less_equal
[ True  True]


Write a NumPy program to create an array with the values
1, 7, 13, 105 and determine the size of the memory occupied
by the array.

In [7]:
import numpy as np

X = np.array([1, 7, 13, 105])

print("Original array:")
print(X)

print("Size of the memory occupied by the given array:")
print("%d bytes" % (X.size * X.itemsize))

Original array:
[  1   7  13 105]
Size of the memory occupied by the said array:
32 bytes


Write a NumPy program to create an array of integers
from 30 to 70.

In [8]:
import numpy as np

array = np.arange(30, 71)

print("Array of the integers from 30 to 70")

print(array)

Array of the integers from 30 to 70
[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


Write a NumPy program to create an array of all even
integers from 30 to 70.

In [11]:
import numpy as np

# Creating an array of even integers from 30 to 70 (inclusive) with a step size of 2 using np.arange()
array = np.arange(30,71,2)

print("Array of the all even integers from 30 to 70")

print(array)

Array of the all even integers from 30 to 70
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


Write a NumPy program to create a 3x3 identity matrix.
Write a search NumPy program to create a 3X4 array and
iterate over it.

In [12]:
import numpy as np

array_2D = np.identity(3)

print('3x3 matrix:')

print(array_2D)

3x3 matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
